variables:
  DOCKER_IMAGE: prateek937/testapp
  DOCKER_TAG: latest

# Using a more complete base image
image: alpine:3.18

services:
  - docker:dind

stages:
  - build

# Install necessary tools before running stages
before_script:
  - apk add --no-cache curl wget unzip docker-cli bash openssl

build_docker:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
  script:
    # Login to Docker Hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
    # Build the Docker image
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG ./app/
    
    # Push the image to Docker Hub
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    
    # Tag and push with commit SHA for versioning
    - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
  variables:
    DOCKER_USERNAME: ${DOCKER_USERNAME}
    DOCKER_PASSWORD: ${DOCKER_PASSWORD} 